{
 "title": "Explore a GBIF dataset - Botany v1",
 "time": { "from": "now-25y", "to": "now" },
 "templating": {
  "list": [
   { "name": "search", "label": "Search" },
   { "name": "scientificname", "label": "Scientific name" },
   { "name": "recordedby", "label": "Recorded by" },
   { "name": "locality", "label": "Locality" },
   { "name": "maxLon", "query": "1" },
   { "name": "minLat", "query": "2" },
   { "name": "minLon", "query": "3" },
   { "name": "maxLat", "query": "4" }
  ]
 },
 "panels": [
  {
   "title": "Graph",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "set search_path to explore,public;\n\nSELECT time, hll_cardinality(hll_union_agg(hll_gbifid)) AS total_records_cube1\nFROM explore.gbif_aggregated\nWHERE $__timeFilter(time)\nAND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\nAND EXISTS\n( WITH a AS (\n  select hll_cardinality(hll_union_agg(hll_gbifid)) AS bla\n  from explore.gbif_aggregated\n  WHERE $__timeFilter(time)\n  AND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n) SELECT 1 FROM a WHERE bla >= 50000 )\nGROUP BY 1\n\nUNION ALL\n\nSELECT time, count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\n--AND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\nAND EXISTS\n( WITH a AS (\n  SELECT GREATEST(hll_cardinality(hll_union_agg(hll_gbifid)),0) AS bla\n  FROM explore.gbif_aggregated\n  WHERE $__timeFilter(time)\n  AND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n) SELECT 1 FROM a WHERE bla < 50000 )\nGROUP BY 1\n\nUNION ALL\n\n(SELECT time, count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NOT NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\nAND tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname')\n--AND tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby')\nGROUP BY 1\nORDER BY 2 DESC)\n\nUNION ALL\n\n(SELECT time, count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NOT NULL)\n--AND tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname')\nAND tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby')\nGROUP BY 1\nORDER BY 2 DESC)\n\nUNION ALL\n\n(SELECT time, count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NOT NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NOT NULL)\nAND tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname')\nAND tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby')\nGROUP BY 1\nORDER BY 2 DESC)\n"
    }
   ]
  },
  {
   "title": "Selected records gbif_enriched",
   "type": "stat",
   "description": "Based on time and location",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "set search_path to explore,public;\n\nSELECT count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND (tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') OR NULLIF('$scientificname', '') IS null)\nAND (tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') OR NULLIF('$recordedby', '') IS null)\n"
    }
   ]
  },
  {
   "title": "Selected records gbif_aggregated",
   "type": "stat",
   "description": "Based on time and location",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "set search_path to explore,public;\n\nSELECT GREATEST(hll_cardinality(hll_union_agg(hll_gbifid)), 0)\nFROM explore.gbif_aggregated\nWHERE $__timeFilter(time)\nAND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n\n"
    }
   ]
  },
  {
   "title": "All records",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "set search_path to explore,public;\n\nSELECT hll_cardinality(hll_union_agg(hll_gbifid)) \nFROM explore.gbif_aggregated"
    }
   ]
  },
  {
   "title": "Distinct scientificname",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "set search_path to explore,public;\n\nSELECT hll_cardinality(hll_union_agg(hll_scientificname)) \nFROM explore.gbif_aggregated\nWHERE $__timeFilter(time)\nAND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n--AND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), centro_id)\n--AND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)"
    }
   ]
  },
  {
   "title": "Distinct recordedby ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "set search_path to explore,public;\n\nSELECT hll_cardinality(hll_union_agg(hll_recordedby)) \nFROM explore.gbif_aggregated\nWHERE $__timeFilter(time)\nAND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n--AND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), centro_id)\n--AND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)"
    }
   ]
  },
  {
   "title": "Distinct locality",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "set search_path to explore,public;\n\nSELECT hll_cardinality(hll_union_agg(hll_locality)) \nFROM explore.gbif_aggregated\nWHERE $__timeFilter(time)\nAND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n--AND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), centro_id)\n--AND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)"
    }
   ]
  },
  {
   "title": "Distinct clusters",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "set search_path to explore,public;\n\nSELECT hll_cardinality(hll_union_agg(hll_cluster_id)) \nFROM explore.gbif_aggregated\nWHERE $__timeFilter(time)\nAND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n--AND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), centro_id)\n--AND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)"
    }
   ]
  },
  {
   "title": "Top scientificname",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SET search_path TO explore,public;\n\nSELECT (topn(topn_union_agg(topn_scientificname), 15)).*\nFROM explore.gbif_aggregated\nWHERE $__timeFilter(time)\nAND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\nAND EXISTS\n( WITH a AS (\n  select hll_cardinality(hll_union_agg(hll_gbifid)) AS bla\n  from explore.gbif_aggregated\n  WHERE $__timeFilter(time)\n  AND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n) SELECT 1 FROM a WHERE bla >= 50000 )\n\nUNION ALL\n\n(SELECT scientificname, count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\nAND EXISTS\n( WITH a AS (\n  SELECT GREATEST(hll_cardinality(hll_union_agg(hll_gbifid)),0) AS bla\n  FROM explore.gbif_aggregated\n  WHERE $__timeFilter(time)\n  AND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n) SELECT 1 FROM a WHERE bla < 50000 )\nGROUP BY 1\nORDER BY 2 DESC)\n\nUNION ALL\n\n(SELECT scientificname, count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NOT NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\nAND tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname')\n--AND tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby')\nGROUP BY 1\nORDER BY 2 DESC)\n\nUNION ALL\n\n(SELECT scientificname, count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NOT NULL)\n--AND tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname')\nAND tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby')\nGROUP BY 1\nORDER BY 2 DESC)\n\nUNION ALL\n\n(SELECT scientificname, count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NOT NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NOT NULL)\nAND tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname')\nAND tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby')\nGROUP BY 1\nORDER BY 2 DESC)\n"
    }
   ]
  },
  {
   "title": "Top recordedby",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 6 },
   "targets": [
    {
     "rawSql": "SET search_path TO explore,public;\n\nSELECT (topn(topn_union_agg(topn_recordedby), 15)).*\nFROM explore.gbif_aggregated\nWHERE $__timeFilter(time)\nAND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\nAND EXISTS\n( WITH a AS (\n  select hll_cardinality(hll_union_agg(hll_gbifid)) AS bla\n  from explore.gbif_aggregated\n  WHERE $__timeFilter(time)\n  AND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n) SELECT 1 FROM a WHERE bla >= 50000 )\n\nUNION ALL\n\n(SELECT recordedby, count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\nAND EXISTS\n( WITH a AS (\n  SELECT GREATEST(hll_cardinality(hll_union_agg(hll_gbifid)),0) AS bla\n  FROM explore.gbif_aggregated\n  WHERE $__timeFilter(time)\n  AND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n) SELECT 1 FROM a WHERE bla < 50000 )\nGROUP BY 1\nORDER BY 2 DESC\nLIMIT 15)\n\nUNION ALL\n\n(SELECT recordedby, count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NOT NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\nAND tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname')\n--AND tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby')\nGROUP BY 1\nORDER BY 2 DESC)\n\nUNION ALL\n\n(SELECT recordedby, count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NOT NULL)\n--AND tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname')\nAND tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby')\nGROUP BY 1\nORDER BY 2 DESC)\n\nUNION ALL\n\n(SELECT recordedby, count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NOT NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NOT NULL)\nAND tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname')\nAND tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby')\nGROUP BY 1\nORDER BY 2 DESC)\n"
    }
   ]
  },
  {
   "title": "Top locality",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "rawSql": "SET search_path TO explore,public;\n\nSELECT  (topn(topn_union_agg(topn_locality), 15)).*\nFROM explore.gbif_aggregated\nWHERE $__timeFilter(time)\nAND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\nAND EXISTS\n( WITH a AS (\n  select hll_cardinality(hll_union_agg(hll_gbifid)) AS bla\n  from explore.gbif_aggregated\n  WHERE $__timeFilter(time)\n  AND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n) SELECT 1 FROM a WHERE bla >= 50000 )\nUNION ALL\nSELECT locality, count(*)\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND (tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') OR NULLIF('$scientificname', '') IS null)\nAND EXISTS\n( WITH a AS (\n  SELECT GREATEST(hll_cardinality(hll_union_agg(hll_gbifid)),0) AS bla\n  FROM explore.gbif_aggregated\n  WHERE $__timeFilter(time)\n  AND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n) SELECT 1 FROM a WHERE bla < 50000 )\nGROUP BY 1\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Map",
   "type": "alexandra-trackmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "(WITH a AS (\nSELECT \ngeom, gbifid,\nCOUNT(gbifid) OVER() AS cnt\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND EXISTS\n( WITH a AS (\n  SELECT GREATEST(hll_cardinality(hll_union_agg(hll_gbifid)),0) AS bla\n  from explore.gbif_aggregated\n  WHERE $__timeFilter(time)\n  AND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n) SELECT 1 FROM a WHERE bla <= 50000 ) \nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\n), b AS (\nSELECT\ngeom, gbifid,\nST_ClusterKMeans(geom, LEAST(cnt::integer, 100)) OVER() AS clusters\nFROM a\n)\nSELECT\nclusters,\n--ST_Y (ST_Transform (ST_Centroid(geom), 4326)) AS latitude,\n--ST_X (ST_Transform (ST_Centroid(geom), 4326)) AS longitude,\nCOUNT(DISTINCT gbifid) AS tooltip,\nAVG(ST_Y (ST_Transform (geom, 4326))) AS latitude,\nAVG(ST_X (ST_Transform (geom, 4326))) AS longitude\nFROM b\nGROUP BY 1\nORDER BY 1)\n\nUNION ALL\n\n(WITH a AS (\nSELECT \nconcave, \nROUND(hll_cardinality(hll_union_agg(hll_gbifid))::int,0) AS tooltip\nFROM explore.gbif_aggregated\nWHERE $__timeFilter(time)\nAND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\nAND EXISTS\n( WITH a AS (\n  select hll_cardinality(hll_union_agg(hll_gbifid)) as bla\n  from explore.gbif_aggregated\n  WHERE $__timeFilter(time)\n  AND ST_intersects(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), concave)\n) SELECT 1 FROM a WHERE bla > 50000 )\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\nGROUP BY 1\n)\nSELECT\n1 AS clusters,\ntooltip,\nST_Y (ST_Transform (ST_Centroid(concave), 4326)) AS latitude,\nST_X (ST_Transform (ST_Centroid(concave), 4326)) AS longitude\nFROM a\n)\n\nUNION ALL\n\n(WITH a AS (\nSELECT \ngeom, gbifid,\nCOUNT(gbifid) OVER() AS cnt\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NOT NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\nAND tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') --OR NULLIF('$scientificname', '') IS null)\n--AND (tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') OR NULLIF('$recordedby', '') IS null)\n), b AS (\nSELECT\ngeom, gbifid,\nST_ClusterKMeans(geom, LEAST(cnt::integer, 100)) OVER() AS clusters\nFROM a\n)\nSELECT\nclusters,\n--ST_Y (ST_Transform (ST_Centroid(geom), 4326)) AS latitude,\n--ST_X (ST_Transform (ST_Centroid(geom), 4326)) AS longitude,\nCOUNT(DISTINCT gbifid) AS tooltip,\nAVG(ST_Y (ST_Transform (geom, 4326))) AS latitude,\nAVG(ST_X (ST_Transform (geom, 4326))) AS longitude\nFROM b\nGROUP BY 1\nORDER BY 1)\n\nUNION ALL\n\n(WITH a AS (\nSELECT \ngeom, gbifid,\nCOUNT(gbifid) OVER() AS cnt\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NOT NULL)\n--AND (tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') OR NULLIF('$scientificname', '') IS null)\nAND tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') --OR NULLIF('$recordedby', '') IS null)\n--GROUP BY 1\n), b AS (\nSELECT\ngeom, gbifid,\nST_ClusterKMeans(geom, LEAST(cnt::integer, 100)) OVER() AS clusters\nFROM a\n)\nSELECT\nclusters,\n--ST_Y (ST_Transform (ST_Centroid(geom), 4326)) AS latitude,\n--ST_X (ST_Transform (ST_Centroid(geom), 4326)) AS longitude,\nCOUNT(DISTINCT gbifid) AS tooltip,\nAVG(ST_Y (ST_Transform (geom, 4326))) AS latitude,\nAVG(ST_X (ST_Transform (geom, 4326))) AS longitude\nFROM b\nGROUP BY 1\nORDER BY 1)\n\nUNION ALL\n\n(WITH a AS (\nSELECT \ngeom, gbifid,\nCOUNT(gbifid) OVER() AS cnt\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NOT NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NOT NULL)\nAND tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') --OR NULLIF('$scientificname', '') IS null)\nAND tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') --OR NULLIF('$recordedby', '') IS null)\n--GROUP BY 1\n), b AS (\nSELECT\ngeom, gbifid,\nST_ClusterKMeans(geom, LEAST(cnt::integer, 100)) OVER() AS clusters\nFROM a\n)\nSELECT\nclusters,\n--ST_Y (ST_Transform (ST_Centroid(geom), 4326)) AS latitude,\n--ST_X (ST_Transform (ST_Centroid(geom), 4326)) AS longitude,\nCOUNT(DISTINCT gbifid) AS tooltip,\nAVG(ST_Y (ST_Transform (geom, 4326))) AS latitude,\nAVG(ST_X (ST_Transform (geom, 4326))) AS longitude\nFROM b\nGROUP BY 1\nORDER BY 1)\n\n\n"
    }
   ]
  },
  {
   "title": "Table explore.grouped using OR",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT time, \n--count(*) over (), \nscientificname, recordedby, locality FROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND (tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') OR NULLIF('$scientificname', '') IS null)\nAND (tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') OR NULLIF('$recordedby', '') IS null)\n--AND (locality IN ('$locality') OR NULLIF('$locality', '') IS null)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Table explore.grouped using UNION ALL and EXISTS",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT time, recordedby, locality, scientificname\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\n--AND scientificname % '$scientificname'\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\n--AND locality % ('$locality')\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\nAND ST_contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nUNION ALL\n\nSELECT time, recordedby, locality, scientificname\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\n--AND scientificname IN ('$scientificname')\nAND (tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') OR NULLIF('$scientificname', '') IS null)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NOT NULL)\n--AND locality IN ('$locality')\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NULL)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nUNION ALL\n\nSELECT time, recordedby, locality, scientificname \nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\n--AND scientificname % '$scientificname'\n--AND (tsv @@ websearch_to_tsquery('simple', '$scientificname') OR NULLIF('$scientificname', '') IS null)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NOT NULL)\nAND (tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') OR NULLIF('$recordedby', '') IS null)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\n\nUNION ALL\n\nSELECT time, recordedby, locality, scientificname\nFROM explore.gbif_enriched\nWHERE $__timeFilter(time)\n--AND scientificname IN ('$scientificname')\nAND (tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') OR NULLIF('$scientificname', '') IS null)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$scientificname')), '') IS NOT NULL)\nAND EXISTS (SELECT 1 WHERE NULLIF(TRIM(CONCAT('$recordedby')), '') IS NOT NULL)\nAND (tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') OR NULLIF('$recordedby', '') IS null)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\n\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Table explore.grouped using TRUE FALSE",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT time, \n--count(*) over (), \nrecordedby, scientificname, locality FROM explore.gbif_enriched\nWHERE $__timeFilter(time)\nAND (tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') AND NULLIF(TRIM(CONCAT('$scientificname')), '') IS NOT NULL) = CASE WHEN NULLIF(TRIM(CONCAT('$scientificname')), '') is null THEN not true ELSE true END\nAND (tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') AND NULLIF(TRIM(CONCAT('$recordedby')), '') IS NOT NULL) = CASE WHEN NULLIF(TRIM(CONCAT('$recordedby')), '') is null THEN not true ELSE true END\n--AND (locality IN ('$locality') AND NULLIF(TRIM(CONCAT('$locality')), '') IS NOT NULL) = CASE WHEN NULLIF(TRIM(CONCAT('$locality')), '') is null THEN not true ELSE true END\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\nLIMIT 100"
    }
   ]
  },
  { "title": "scientificname totals", "type": "table", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 } },
  { "title": "Table explore.cube", "type": "table", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 } },
  {
   "title": "Top 3 province per month",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Total count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Distinct scientificname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ]
  }
 ]
}