{
 "title": "Explore a GBIF dataset - Botany v2",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   { "name": "minLat", "query": "${VAR_MINLAT}" },
   { "name": "maxLat", "query": "${VAR_MAXLAT}" },
   { "name": "minLon", "query": "${VAR_MINLON}" },
   { "name": "maxLon", "query": "${VAR_MAXLON}" },
   { "name": "search", "label": "Search" },
   { "name": "recordedby", "label": "Recorded by" },
   { "name": "scientificname", "label": "Scientificname" },
   {
    "name": "preparations",
    "label": "Preparations method",
    "query": "SELECT DISTINCT preparations FROM explore.gbif_enriched ORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Map",
   "type": "alexandra-trackmap-panel",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH a AS (\nSELECT\ngeom, gbifid,\nCOUNT(gbifid) OVER() AS cnt\nFROM explore.gbif_enriched\nLEFT JOIN explore.recordedby ON gbif_enriched.recordedby_id = recordedby.id\n--LEFT JOIN explore.multimedia b USING (gbifid)\nWHERE $__timeFilter(eventdate)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\n--AND (tsv @@ websearch_to_tsquery('simple', '$search') OR NULLIF('$search', '') IS null)\nAND (tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') OR NULLIF('$recordedby', '') IS null)\n--AND (recordedby.name % '$recordedby' OR NULLIF('$recordedby', '') IS null)\nAND (tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') OR NULLIF('$scientificname', '') IS null)\nAND (preparations IN ($preparations) OR NULLIF(TRIM(CONCAT($preparations)), '') IS null)\n--AND (b.type IN ($multimedia) OR NULLIF(TRIM(CONCAT($multimedia)), '') IS null)\n), b AS (\nSELECT\ngeom, gbifid,\nST_ClusterKMeans(geom, LEAST(cnt::integer, 100)) OVER() AS clusters\nFROM a\n)\nSELECT clusters,\nCOUNT(DISTINCT gbifid) AS tooltip,\nAVG(ST_Y (ST_Transform (geom, 4326))) AS latitude,\nAVG(ST_X (ST_Transform (geom, 4326))) AS longitude\nFROM b\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT gbifid), \n  $__time(eventdate)\nFROM explore.gbif_enriched\nLEFT JOIN explore.recordedby ON gbif_enriched.recordedby_id = recordedby.id\n--LEFT JOIN explore.multimedia b USING (gbifid)\nWHERE $__timeFilter(eventdate)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\n--AND (tsv @@ websearch_to_tsquery('simple', '$search') OR NULLIF('$search', '') IS null)\nAND (tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') OR NULLIF('$recordedby', '') IS null)\n--AND (recordedby.name % '$recordedby' OR NULLIF('$recordedby', '') IS null)\nAND (tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') OR NULLIF('$scientificname', '') IS null)\nAND (preparations IN ($preparations) OR NULLIF(TRIM(CONCAT($preparations)), '') IS null)\n--AND (b.type IN ($multimedia) OR NULLIF(TRIM(CONCAT($multimedia)), '') IS null)\nGROUP BY 2\n--ORDER BY 2 ASC"
    }
   ]
  },
  {
   "title": "Recorded by",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT gbifid), recordedby\nFROM explore.gbif_enriched\nLEFT JOIN explore.recordedby ON gbif_enriched.recordedby_id = recordedby.id\n--LEFT JOIN explore.multimedia b USING (gbifid)\nWHERE $__timeFilter(eventdate)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\n--AND (tsv @@ websearch_to_tsquery('simple', '$search') OR NULLIF('$search', '') IS null)\nAND (tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') OR NULLIF('$recordedby', '') IS null)\n--AND (recordedby.name % '$recordedby' OR NULLIF('$recordedby', '') IS null)\nAND (tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') OR NULLIF('$scientificname', '') IS null)\nAND (preparations IN ($preparations) OR NULLIF(TRIM(CONCAT($preparations)), '') IS null)\n--AND (b.type IN ($multimedia) OR NULLIF(TRIM(CONCAT($multimedia)), '') IS null)\nGROUP BY 2\nORDER BY 1 DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Scientificname",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT gbifid), scientificname\nFROM explore.gbif_enriched\nLEFT JOIN explore.recordedby ON gbif_enriched.recordedby_id = recordedby.id\n--LEFT JOIN explore.multimedia b USING (gbifid)\nWHERE $__timeFilter(eventdate)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\n--AND (tsv @@ websearch_to_tsquery('simple', '$search') OR NULLIF('$search', '') IS null)\nAND (tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') OR NULLIF('$recordedby', '') IS null)\n--AND (recordedby.name % '$recordedby' OR NULLIF('$recordedby', '') IS null)\nAND (tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') OR NULLIF('$scientificname', '') IS null)\nAND (preparations IN ($preparations) OR NULLIF(TRIM(CONCAT($preparations)), '') IS null)\n--AND (b.type IN ($multimedia) OR NULLIF(TRIM(CONCAT($multimedia)), '') IS null)\nGROUP BY 2\nORDER BY 1 DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Preparation method",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT gbifid), preparations\nFROM explore.gbif_enriched\nLEFT JOIN explore.recordedby ON gbif_enriched.recordedby_id = recordedby.id\n--LEFT JOIN explore.multimedia b USING (gbifid)\nWHERE $__timeFilter(eventdate)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\n--AND (tsv @@ websearch_to_tsquery('simple', '$search') OR NULLIF('$search', '') IS null)\nAND (tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') OR NULLIF('$recordedby', '') IS null)\n--AND (recordedby.name % '$recordedby' OR NULLIF('$recordedby', '') IS null)\nAND (tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') OR NULLIF('$scientificname', '') IS null)\nAND (preparations IN ($preparations) OR NULLIF(TRIM(CONCAT($preparations)), '') IS null)\n--AND (b.type IN ($multimedia) OR NULLIF(TRIM(CONCAT($multimedia)), '') IS null)\nGROUP BY 2\nORDER BY 1 DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT a.gbifid, a.eventdate, a.scientificname, a.catalognumber, a.occurrenceid, a.recordedby, a.preparations, a.locality\n--(array_agg(b.identifier))[1] AS image, to_jsonb(array_agg(b.identifier)) AS image_urls\nFROM explore.gbif_enriched a\nLEFT JOIN explore.recordedby ON a.recordedby_id = recordedby.id\n--LEFT JOIN explore.multimedia b USING (gbifid)\nWHERE $__timeFilter(eventdate)\nAND ST_Contains(st_geometryfromtext('POLYGON(($maxLon $minLat, $maxLon $maxLat, $minLon $maxLat, $minLon $minLat,$maxLon $minLat))',4326), geom)\n--AND (tsv @@ websearch_to_tsquery('simple', '$search') OR NULLIF('$search', '') IS null)\nAND (tsv_recordedby @@ websearch_to_tsquery('simple', '$recordedby') OR NULLIF('$recordedby', '') IS null)\n--AND (recordedby.name % '$recordedby' OR NULLIF('$recordedby', '') IS null)\nAND (tsv_scientificname @@ websearch_to_tsquery('simple', '$scientificname') OR NULLIF('$scientificname', '') IS null)\nAND (preparations IN ($preparations) OR NULLIF(TRIM(CONCAT($preparations)), '') IS null)\n--AND (b.type IN ($multimedia) OR NULLIF(TRIM(CONCAT($multimedia)), '') IS null)\n--GROUP BY 1\nORDER BY eventdate DESC\nLIMIT 100"
    }
   ]
  }
 ]
}