apiVersion: 1
datasources:
  - name: bioclouddb
    type: postgres
    url: postgres
    database: db1
    user: postgres
    isDefault: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: "disable"      # disable/require/verify-ca/verify-full
      maxOpenConns: 0         # Grafana v5.4+
      maxIdleConns: 2         # Grafana v5.4+
      connMaxLifetime: 14400  # Grafana v5.4+
      postgresVersion: 1400   # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: true
